In [ ]:
# 데이터 전처리가 끝났음에도 너무 많아서 랜덤으로 2만개 정도의 샘플만 사용할 것이다.
# sample 함수 이용

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 모듈 불러오기 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import gc
import os
import sys
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [ ]:
# 전처리를 완료한 csv의 경로 설정
path = '/content/drive/MyDrive/PUBG/train_V2.csv'

In [ ]:
# 메모리 줄여주는 함수
def reduce_mem_usage(df):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.
    """
    start_mem = df.memory_usage().sum() / 1024**2
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                #if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                #    df[col] = df[col].astype(np.float16)
                #el
                if c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        #else:
            #df[col] = df[col].astype('category')

    end_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage of dataframe is {:.2f} MB --> {:.2f} MB (Decreased by {:.1f}%)'.format(
        start_mem, end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df

In [ ]:
train = pd.read_csv(path)
train = reduce_mem_usage(train)

print(train.shape)

Memory usage of dataframe is 983.90 MB --> 339.28 MB (Decreased by 65.5%)
(4446966, 29)


In [ ]:
train.groupby("matchId").first()

Id         groupId  ...  winPoints  winPlacePerc
matchId                                         ...                         
0000a43bce5eec  a121348062f67a  7bd08592bb25e2  ...       1502        0.6667
0000eb01ea6cdd  f206898929bcd0  e89636a86735d3  ...          0        0.7778
0002912fe5ed71  514b1b621153b0  34e5e1dce2df52  ...          0        0.7128
0003b92987589e  0da9cdffa2c38c  f66e431c782807  ...          0        0.9592
0006eb8c17708d  c853bfaa6a2042  60092e8db28284  ...       1440        0.1522
...                        ...             ...  ...        ...           ...
fffd74b5150cb4  8f2b384858bde1  13105852cafe74  ...       1458        0.0714
fffe53015be300  1fecfeb9bec37c  0dcff9a13d53f7  ...          0        0.9375
fffe562611d981  200441bf330c56  5f74b1e18d8c96  ...       1482        0.3200
fffe721f841f85  0ad7a09f418a76  c5ba82f359b0d8  ...       1568        0.6667
fffe92232706aa  9db61c9d81b503  14fdb6c222eff7  ...          0        0.1071

[47965 rows x 28 columns]

In [ ]:
# 랜덤으로 행을 추출하기 때문에 
# 돌릴때마다 달라짐 주의
ol = train['matchId'].sample(n = 1000)

In [ ]:
# isin함수를 활용하기 위해 리스트화 한다.
ol = list(ol)

In [ ]:
ol

['5846debb119491',
 '48e5f174a59481',
 '3fb5b9da01e69d',
 'f0d4741a411e53',
 'db41a31e6c961a',
 '0227b0bc591912',
 '03d43462aac764',
 '6d767bb2a36410',
 'ef86bec4c4ad0b',
 'f7d284ffb9d8ff',
 '9ede787e2afd04',
 'e3fbc4d641aa14',
 '1b42de85a35873',
 'a2662f82e8bb00',
 '9c570795d069dc',
 '79cbbbd53d1988',
 '1acec05e2a8ff1',
 'e0e862a7ed1ca2',
 '3375eb619fc1e1',
 'a76481741cbb0e',
 '7794deb4b065ab',
 '23ddbc5f0052f9',
 '895ea854084e86',
 'fdcf7d24d6122d',
 '3f8725caa351e1',
 '7b61fa3ea82c15',
 'b8a40e72985a42',
 '9af60e4a633c44',
 'b3f140aea3966a',
 '184b465519700e',
 '74d959795df4b5',
 'cbc3665d093dbc',
 'e46b0d4ad4d84c',
 '88fcbe5d909fa1',
 'fba7649bef9829',
 'd0296893b255eb',
 '2b1d28cde3a775',
 '6856803d00d117',
 '7b260ee8204768',
 '232ed14d622332',
 '0f4b0c6c413212',
 '2000dd830f79a3',
 '084429f410d099',
 'f1582a02748396',
 '421867f5c10a96',
 'edd676450a5c63',
 'b40f7774203771',
 '1d57d4620efff9',
 '318ec9adf590aa',
 '4fee09cf1e4350',
 'd4744a68993e44',
 '78896ca5eeedf2',
 '1956cb2ac6

In [ ]:
# 해당 매치에 있는것만 남긴다
inner = train[train['matchId'].isin(ol)]

del train
gc.collect()

104

In [ ]:
print(inner.shape)

(93185, 29)


In [ ]:
all_data = inner.copy()

del inner
gc.collect()

print(all_data.shape)

(93185, 29)


# RandomForest

In [ ]:
# 강사님의 자전거 대여횟수 예측 모델을 참고함
# 종속변수인 winPlacePerc 를 y에 대입
y = all_data["winPlacePerc"]
y.head()

6      0.0000
179    0.0357
216    0.1111
442    0.0345
447    0.8276
Name: winPlacePerc, dtype: float32

In [ ]:
# 데이터를 X에 대입
X= all_data.copy()
# X 에서 count컬럼 삭제
X.pop("winPlacePerc")
X.head()

Id         groupId  ... weaponsAcquired  winPoints
6    95959be0e21ca3  2c485a1ad3d0f1  ...               1       1497
179  8ba88024464ac7  fceaceee1037da  ...               1          0
216  9bf22ece15e8c1  d6621cbf8b7bfa  ...               1       1508
442  d35455eb0eefd3  641f95626b16c6  ...               1          0
447  923fb2cec0e720  24f955b0057aa0  ...               5          0

[5 rows x 28 columns]

In [ ]:
# 데이터 분할
from sklearn.model_selection import train_test_split
# 전체 데이터 중 20%를 X_test,y_test 에 대입
# 나머지 80%를 X_train,y_train 에 대입
# random_state = 777을 부여 동일한 결과가 나오도록 세팅
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 777)

In [ ]:
# 모두 numberic이지만 ID 관련 정보는 numberic화 하지 않아서 제거할 예정인데
# 나중에 다시 붙일 수 있도록 변수화 해준다

X_test_grp = X_test[['matchId','groupId']].copy()

train_matchId = X_train['matchId']


In [ ]:
# ID 관련 col들을 드롭해준다.

X_train.drop(['matchId','groupId','Id','matchType'], axis=1, inplace=True)
X_test.drop(['matchId','groupId','Id','matchType'], axis=1, inplace=True)

In [ ]:
# 날아갔나 확인 
X_train.head()

assists  boosts  damageDealt  ...  walkDistance  weaponsAcquired  winPoints
2839683        1       2   137.699997  ...   2429.000000                7          0
1696468        0       0    19.100000  ...    981.700012                4          0
3532415        0       1   363.299988  ...   2203.000000                6       1614
4318739        0       1    44.980000  ...   1638.000000                3          0
3542209        0       0   300.000000  ...     37.500000                1          0

[5 rows x 24 columns]

In [ ]:
# RandomForestRegressor: RandomForest 알고리즘을 이용해서 값을 예측(회귀)
from sklearn.ensemble import RandomForestRegressor
# RandomForestRegressor 객체 생성
rf_model=RandomForestRegressor(
    random_state = 0 # 같은 값을 설정하면 다음에 실행할때 같은 행을 선택
    
    )

In [ ]:
# RandomForestRegressor(RandomForest 알고리즘을 이용해서 값을 예측(회귀)) 객체 출력
rf_model

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
# X_train을 독립 변수로 y_train을 예측하는 의사 결정 트리들을 생성
rf_model.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
# X_test를 가지고 예측 
pred_rf =rf_model.predict(X_test)

In [ ]:
pred_rf

array([0.141474  , 0.877345  , 0.173435  , ..., 0.712579  , 0.52972407,
       0.355776  ])

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
# 진짜값 y_test 와 예측값 pred의 잔차제곱합인 MSE를 계산 

print ("RF의 MSE: ", mean_squared_error(y_test, pred_rf))

RF의 MSE:  0.007172469190640076


# XGBoost

In [ ]:
# 필요한 데이터 모듈 불러오기
from xgboost import XGBRegressor

In [ ]:
# XGboost
model_xgb = XGBRegressor(random_state = 0)

In [ ]:
model_xgb.fit(X_train, y_train)

[08:00:32] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
pred_XGb = model_xgb.predict(X_test)

In [ ]:
pred_XGb

array([0.13646099, 0.82082105, 0.18990755, ..., 0.72800064, 0.46302187,
       0.36811078], dtype=float32)

In [ ]:
print ("XGB의 MSE : ", mean_squared_error(pred_XGb, y_test))

XGB의 MSE :  0.008765104


# Light Gradient Boosting Machine

In [ ]:
# 모듈 불러오기
from lightgbm import LGBMRegressor

In [ ]:
# 객체생성 
model_lgb = LGBMRegressor(random_state = 0)

In [ ]:
# 모델학습
model_lgb.fit(X_train, y_train)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=0, reg_alpha=0.0, reg_lambda=0.0, silent=True,
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
# 예측
pred_LGB = model_lgb.predict(X_test)

In [ ]:
# 예측 확인
pred_LGB

array([0.14006304, 0.80859489, 0.18106268, ..., 0.6832199 , 0.52398358,
       0.31991504])

In [ ]:
print ("MSE: ", mean_squared_error(pred_LGB, y_test))

MSE:  0.006510948021587913


# Extra Trees Regressor

In [ ]:
# 모듈 불러오기 
from sklearn.ensemble import ExtraTreesRegressor

# 모델 객체 생성
et_model=ExtraTreesRegressor(
    random_state = 0 # 같은 값을 설정하면 다음에 실행할때 같은 행을 선택    
    )

In [ ]:
# 모델 생성 확인 
et_model

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=None, oob_score=False,
                    random_state=0, verbose=0, warm_start=False)

In [ ]:
# 모델 학습
et_model.fit(X_train,y_train)

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=None, oob_score=False,
                    random_state=0, verbose=0, warm_start=False)

In [ ]:
# X_test를 가지고 예측 
pred_et = et_model.predict(X_test)

In [ ]:
# 생성확인
pred_et

array([0.143474, 0.878186, 0.177796, ..., 0.674632, 0.536754, 0.358584])

In [ ]:
print ("MSE - et : ", mean_squared_error(y_test, pred_et))

MSE - et :  0.00708911839349509


# 결과

In [ ]:
total = pd.DataFrame({'name':['Random Forest', 'XGBoost', 'LGB','Extra Tree'],
                             'MSE':[mean_squared_error(y_test, pred_rf), mean_squared_error(y_test, pred_XGb),mean_squared_error(y_test, pred_LGB),mean_squared_error(y_test, pred_et)],
                             'MAE':[mean_absolute_error(y_test, pred_rf), mean_absolute_error(y_test, pred_XGb),mean_absolute_error(y_test, pred_LGB),mean_absolute_error(y_test, pred_et)]})

In [ ]:
total

name       MSE       MAE
0  Random Forest  0.007172  0.059671
1        XGBoost  0.008765  0.066842
2            LGB  0.006511  0.057887
3     Extra Tree  0.007089  0.059856